### PR TITLE
Make AsyncBytes and AsyncLineSequence not conflict with foundation variants when Darwin is available

### PR DESCRIPTION
**Pull request by doozMen**
When Darwin is available the implementation from Foundation is used.  

For the rest I tried to explain in the commit and/or commit description why I added things. Could you let me know if this would be something you would consider adding or how I can change it to be more like something to include in SwiftCommand.

I have been using `SwiftCommand` now for some time and it runs very smooth and I like working with it. Thanks for adding!

### CODE REVIEW

**Comment by doozMen** [comment]
@Zollerboy1 any news on this?

**Comment by Zollerboy1** [comment]
Hey @doozMen, sorry for my late answer.
I'm glad to hear that you're enjoying using this library.

First of all, you have some random changes in this PR that have nothing to do with your main request and that I wouldn't just merge into my project like that.

Regarding `AsyncBytes`/`AsyncLineSequence`: your approach compiles because you bumped the platform requirements to macOS 12.0, which I dislike. I tried to play around with still having the manual implementations on macOS 10/11, but it doesn't work well (e.g. you'd have to use `if #available` everywhere).
Why do you need to have the `Foundation` types for this? Would it suffice if I provided properties like `ChildProcess.OutputHandle.nativeLines` (that are only available on macOS 12.0 and above) where you get the async sequences from `Foundation`?

**Comment by doozMen** [comment]
Fair answer. I do think I tried describing the random changes in different commit but yes there seams to be a growing sensitivity for that. I tend to follow an old dying principle cleaning up where you pass by but can understand the concern.

My need for having the lines output one by one as they come has been a quest for a long time. I do not seam to get it right as my main goal is to do this on large outputs, like Xcode builds or other processes that are very verbose and I just want to show a line as they match a regex. Unfortunately also with your library on large outputs I seam to have processes halted and never end. 

I only found a solution where set the output to write to a file first and then after read the file line by line. But this does not show output during the process run.

So if you could help me with that `ChildProcess.OutputHandle.nativeLines` that would output for stdError our stdOut while the process is running without the problem that the process seams to run into a memory problem en stops running and never ends that would be greatly appreciated.

As to your question why I need `Foundation`? I try to keep close to what is available in `Foundation` and if it is available there I find it better to use the `Foundation` types instead. But this is just because I cannot write it better then `Foundation`. But if you can feel free to do so.

I appreciate your feedback and will continue using my fork then for now. I close this PR and thanks again for the super library I hope it gains traction and people write more cli tools in Swift.

**Comment by Zollerboy1** [comment]
Hey @doozMen, quick follow-up: `nativeCharacters`, `nativeLines`, and `nativeBytes` are implemented for macOS >= 12 as of version 1.3.0. Please check it out and see if it fits your needs.

Regarding the problems you've had with my custom implementation of these async sequences: could you open an issue about it and include some example code where the problems occur? That would help me tremendously with fixing it.

**Pull request closed without merging**
